### ISSUE TITLE
Scala 2.13 won't compile

### ISSUE THREAD

**Issue by tampler** [higherkindness/mu-scala#923] opened 2020-05-30 19:25 UTC
Hello ! Thanks for a great project. I used your g8 template to generate a stub and integrate it in a main project. This works for Scala 2.12, but fails to compile for 2.13, due to renamed collections.

```bash
[error] (protocol / muSrcGen) java.lang.NoSuchMethodError: 'scala.jdk.CollectionConverters$RichConcurrentHashMap scala.jdk.CollectionConverters$.RichConcurrentHashMap(java.util.concurrent.ConcurrentHashMap)'
[error] (update) sbt.librarymanagement.ResolveException: Error downloading tetra-protocol:tetra-protocol_2.13:0.1.0-SNAPSHOT
```

**Comment by cb372** [comment] 2020-06-01 10:01
Hi, thanks for the report. Unfortunately I can't reproduce the issue.

I ran `sbt new higherkindness/mu-scala.g8` and then `sbt compile` and it worked fine. I tried with both Scala 2.12.11 and 2.13.2, and with both Protobuf and Avro.

However, it looks the same as https://github.com/julianpeeters/avrohugger/issues/131, and we use avrohugger in our sbt plugin to generate Scala code from Avro IDL.

I'll keep trying to reproduce it. Please add any more details you think might be relevant.

**Comment by battermann** [comment] 2020-07-20 14:36
@tampler 
Ran into the same or similar issue.
Could work around it by adding this line to the `plugin.sbt`:

```
dependencyOverrides += "com.julianpeeters" %% "avrohugger-core" % "1.0.0-RC21"
addSbtPlugin("io.higherkindness" %% "sbt-mu-srcgen" % "0.22.3")
```

**Comment by tampler** [comment] 2020-07-20 19:13
Hello, @battermann 

I switched to [zio-grpc](https://github.com/scalapb/zio-grpc) in my work. But I'm glad you have found a resolution. Pls make your PR and improve this library

Thanks for reporting ! 
Boris

**Comment by battermann** [comment] 2020-07-21 07:02
> Hello, @battermann
> 
> I switched to [zio-grpc](https://github.com/scalapb/zio-grpc) in my work. But I'm glad you have found a resolution. Pls make your PR and improve this library
> 
> Thanks for reporting !
> Boris

I could make a PR, but this is a downgrade of the dependency and I don't know if this is the desired fix.
Also I don't know how frequently this problem occurs. In my case it was an interference with another sbt plugin, maybe a very rare case. Not sure if it justifies to solve it by downgrading a dependency?

**Comment by cb372** [comment] 2020-07-21 08:35
@battermann Do you know which plugin it was interfering with? I was never able to reproduce the issue.

**Comment by battermann** [comment] 2020-07-21 08:43
> @battermann Do you know which plugin it was interfering with? I was never able to reproduce the issue.

It's this: https://scalapb.github.io/grpc.html

Compilation fails if this line is added:

```scala
libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.11.0-M2"
```

This is a rare case, because why would you have two different gRPC plugins in the same project?

**Comment by tampler** [comment] 2020-07-21 11:58
I tried this product before I found `zio-grpc`. I'm writing most code with ZIO, so its a simply better coding fit. Nothing wrong with `mu-scala`, its an awesome lib.

Kudos @cb372 for building it. I saw his talk on Scala-in-the-City conference and decided to try

**Comment by julianpeeters** [comment] 2021-02-15 04:15
This should be fixed now in `"com.julianpeeters" %% "avrohugger-core" % "1.0.0-RC23"`

Kudos @targeter for the fix

**Closed** 2021-09-28 12:25 UTC
